exchanges:
  binance:
    allowed_symbols:
    - BTCUSDT
    - ETHUSDT
    - SOLUSDT
    default_market_type: spot
    disabled_products:
    - futures
    - margin
    enabled: true
    live_trading_enabled: false
